# This file was generated by GoReleaser. DO NOT EDIT.
cask "ember" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "a672a647a92de2590fff1faf17ed85c8eb28fbbd78c507f19bd9545a3abe53b2"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0590d75aa2ab5b09507a02fb15d0cda9f74d71a292c16392207046625633d616"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1516656a306c2d6a1a8f954629f906f4126ff099094ec6d6905ed12fc1bda554"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c30c3503da18b062269cd5f51925c5262dd7fae49107cefd5160ac3785463585"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ember"
  desc "Real-time terminal dashboard for Caddy & FrankenPHP"
  homepage "https://github.com/alexandre-daubois/ember"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ember"

  # No zap stanza required

end
