# This file was generated by GoReleaser. DO NOT EDIT.
cask "ember" do
  version "1.1-rc1"

  on_macos do
    on_intel do
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_darwin_amd64.tar.gz"
      sha256 "b04b3db6381665ec62afc79887288ca68268fd79361129bfd73397b823c93faf"
    end
    on_arm do
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_darwin_arm64.tar.gz"
      sha256 "c910476ee9b3b93d3b522ae51be0f7630e51b33440d91b9450b45197cae3060b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_linux_amd64.tar.gz"
      sha256 "6e0aa06b1e2f9484e4630035ab530d697caf4c2485ed958c8b47211081951bdf"
    end
    on_arm do
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_linux_arm64.tar.gz"
      sha256 "ab75afdfd624d739f33d29bda4a5868b742a23e9eb1ea6b07be16a6b7c3923e4"
    end
  end

  name "ember"
  desc "Real-time terminal dashboard for Caddy & FrankenPHP"
  homepage "https://github.com/alexandre-daubois/ember"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ember"

  # No zap stanza required

end
