# This file was generated by GoReleaser. DO NOT EDIT.
cask "ember" do
  version "1.4.3"

  on_macos do
    on_intel do
      sha256 "2902c9d91c0f544d8e26cd7e37608eac0aebc1067c3a20814cb67ca37a5d5c7d"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de739517dae7ede1282d6999fa0caa81e00f3f5fbddbbcfcb56be34580403e2c"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3a6011226180ce99044bdefae88be210e7e9f3f95320f4e82b7cbbd572d114e"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bdd545b769155074184b610682b903ea64cb1648fe8780554db4c3233a8ad3a2"
      url "https://github.com/alexandre-daubois/ember/releases/download/v#{version}/ember_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ember"
  desc "Real-time terminal dashboard for Caddy & FrankenPHP"
  homepage "https://github.com/alexandre-daubois/ember"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ember"

  # No zap stanza required

end
